//Fetch Company Information action types
export const COMPANYINFO_LOADING = "COMPANYINFO_LOADING";
export const COMPANYINFO_SUCCESS = "COMPANYINFO_SUCCESS";
export const COMPANYINFO_FAIL = "COMPANYINFO_FAIL";

//Fetch Jobs info action types
export const JOBS_LOADING = "JOBS_LOADING";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAIL = "FETCH_JOBS_FAIL";

//Fetch Job Detail action types
export const JOB_DETAIL_LOADING = "JOB_DETAIL_LOADING";
export const FETCH_JOB_DETAIL_SCUCCESS = "FETCH_JOB_DETAIL_SCUCCESS";
export const FETCH_JOB_DETAIL_FAIL = "FETCH_JOB_DETAIL_FAIL"

//Fetch Job Apply action types
export const JOB_APPLY_LOADING = "JOB_APPLY_LOADING";
export const FETCH_JOB_APPLY_SUCCESS = "FETCH_JOB_APPLY_SUCCESS ";
export const FETCH_JOB_APPLY_FAIL = "FETCH_JOB_APPLY_FAIL";

//Fetch Job Applied action types
export const LOAD_JOB_APPLIED = "LOAD_JOB_APPLIED";
export const FETCH_JOB_APPLIED_SUCCESS = "FETCH_JOB_APPLIED_SUCCESS ";
export const FETCH_JOB_APPLIED_FAIL = "FETCH_JOB_APPLIED_FAIL";

//Submit Jobs data action types
export const POST_JOB_APPLIED_LOADING = "POST_JOB_APPLIED_LOADING";
export const POST_JOB_APPLIED_SUCCESS = "POST_JOB_APPLIED_SUCCESS";
export const POST_JOB_APPLIED_FAIL = "POST_JOB_APPLIED_FAIL";


//Authentication
export const AUTH_LAODING = "AUTH_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CONFIRM_LOGIN_SUCCESS = "CONFIRM_LOGIN_SUCCESS";
export const CONFIRM_LOGIN_FAIL = "CONFIRM_LOGIN_FAIL";
export const CREATE_PIN_SUCCESS = "CREATE_PIN_SUCCESS";
export const CREATE_PIN_FAIL = "CREATE_PIN_FAIL";
export const CREATE_PASS_SUCCESS = "CREATE_PASS_SUCCESS";
export const CREATE_PASS_FAIL = "CREATE_PASS_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

//Candidates
//Fetch JobTypes action types
export const FETCH_JOB_TYPE_LOADING = "FETCH_JOB_TYPES_LOADING";
export const FETCH_JOB_TYPE_SUCCESS = "FETCH_JOB_TYPES_SUCCESS";
export const FETCH_JOB_TYPE_FAIL = "FETCH_JOB_TYPES_FAIL";

//Fetch JobPositions actionTypes 
export const JOB_POSTIONS_LODING = "JOB_POSITIONS_LODING";
export const FETCH_JOB_POSTIONS_SUCCESS = "FETCH_JOB_POSITIONS_SUCCESS";
export const FETCH_JOB_POSTIONS_FAIL = "FETCH_JOB_POSITIONS_FAIL";

//Jobs Filter action types
export const JOB_FILTER_LOADING = "JOB_FILTER_LOADING";
export const JOB_FILTER_SUCCESS = "JOB_FILTER_SUCCESS";
export const JOB_FILTER_FAIL = "JOB_FILTER_FAIL";

//Intern Filter action types
export const INTERN_FILTER_LOADING = "INTERN_FILTER_LOADING";
export const INTERN_FILTER_SUCCESS = "INTERN_FILTER_SUCCESS";
export const INTERN_FILTER_FAIL = "INTERN_FILTER_FAIL";
